/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package common;

import admin.AdminDashboard;
import dao.NhanVienDao;
import dao.userDao;
import entity.NhanVienEntity;
import entity.userEntity;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import staff.StaffDashboard;
import user.SignUp;
import user.UserDashboard;

/**
 *
 * @author Pham Van Thanh
 */
public class Login extends javax.swing.JFrame {

    private userDao userDAO = new userDao();
    private NhanVienDao nvDAO = new NhanVienDao();

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_Exit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_hide = new javax.swing.JLabel();
        lbl_visible = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JRadioButton();
        btnStaff = new javax.swing.JRadioButton();
        btnUser = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trolley.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TO");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTEEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 440));

        jPanel2.setBackground(new java.awt.Color(25, 118, 221));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Exit.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        lbl_Exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Exit.setText("x");
        lbl_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ExitMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 30, 27));
        lbl_Exit.getAccessibleContext().setAccessibleDescription("");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Login");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 39, 374, -1));

        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 281, 30));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 281, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        lbl_hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hide.png"))); // NOI18N
        lbl_hide.setText("jLabel8");
        lbl_hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_hideMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 30));

        lbl_visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/visible.png"))); // NOI18N
        lbl_visible.setText("jLabel8");
        lbl_visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_visibleMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 30));

        buttonGroup1.add(btnAdmin);
        btnAdmin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("Admin");
        jPanel2.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        buttonGroup1.add(btnStaff);
        btnStaff.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnStaff.setText("Staff");
        jPanel2.add(btnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        buttonGroup1.add(btnUser);
        btnUser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setText("User");
        jPanel2.add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btnLogin.setBackground(new java.awt.Color(204, 204, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(25, 118, 221));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, 40));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Don't have an account ?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setText("Sign Up");
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignUpMouseClicked(evt);
            }
        });
        jPanel2.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Forgot Password");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 370, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_ExitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.1; i <= 1.0; i += 0.1) {
            String s = "" + i;
            float f = Float.parseFloat(s);
            this.setOpacity(f);
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void lbl_hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_hideMouseClicked
        txtPassword.setEchoChar((char) 0);

        lbl_visible.setVisible(true);
        lbl_hide.setVisible(false);
    }//GEN-LAST:event_lbl_hideMouseClicked

    private void lbl_visibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_visibleMouseClicked
        txtPassword.setEchoChar('*');

        lbl_visible.setVisible(false);
        lbl_hide.setVisible(true);
    }//GEN-LAST:event_lbl_visibleMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (checkEmpty()) {
            String username = txtUsername.getText().trim();
            String password = String.valueOf(txtPassword.getPassword()).trim();
            if (btnUser.isSelected()) {
                userEntity user = userDAO.selectUserLogin(username, password);
                if (user == null) {
                    JOptionPane.showMessageDialog(this, "Thông tin tài khoản mật khẩu không chính xác!!", "Warring", 2);
                } else {
                    if(!user.isStatus()){
                        JOptionPane.showMessageDialog(this, "Tài khoản đã bị khóa!!", "Warring", 2);
                        return;
                    }
                    new ToanCuc().setUsername(username);
                    
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!!", "Warring", 2);
                    this.dispose();
                    new UserDashboard().setVisible(true);
                }
            } else if (btnStaff.isSelected()) {
                NhanVienEntity nv = nvDAO.selectNhanVienDangNhap(username, password, 2);
                if (nv == null) {
                    JOptionPane.showMessageDialog(this, "Thông tin tài khoản mật khẩu không chính xác!!", "Warring", 2);
                } else {
                    if(!nv.isStatus()){
                        JOptionPane.showMessageDialog(this, "Tài khoản đã bị khóa!!", "Warring", 2);
                        return;
                    }
                    new ToanCuc().setUsername(username);
                    
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!!", "Warring", 2);
                    this.dispose();
                    new StaffDashboard().setVisible(true);
                }
            }else if (btnAdmin.isSelected()){
                NhanVienEntity nv = nvDAO.selectNhanVienDangNhap(username, password, 1);
                if (nv == null) {
                    JOptionPane.showMessageDialog(this, "Thông tin tài khoản mật khẩu không chính xác!!", "Warring", 2);
                } else {
                    if(!nv.isStatus()){
                        JOptionPane.showMessageDialog(this, "Tài khoản đã bị khóa!!", "Warring", 2);
                        return;
                    }
                    new ToanCuc().setUsername(username);
                    
                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!!", "Warring", 2);
                    this.dispose();
                    new AdminDashboard().setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseClicked
        new SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSignUpMouseClicked

    // kiêm tra có o nao bo trong khong
    private boolean checkEmpty() {
        if (txtUsername.getText().isEmpty() || String.valueOf(txtPassword.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!!", "Warring", 2);
            return false;
        }
        if (!btnUser.isSelected() && !btnAdmin.isSelected() && !btnStaff.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn đối tượng đăng nhập!!", "Warring", 2);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAdmin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JRadioButton btnStaff;
    private javax.swing.JRadioButton btnUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lbl_Exit;
    private javax.swing.JLabel lbl_hide;
    private javax.swing.JLabel lbl_visible;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
