/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package staff;

import staff.ChuyenBan;
import staff.GopBan;
import staff.BanHang;
import common.ToanCuc;
import dao.orderDao;
import dao.tableCanteenDao;
import entity.TableCanteenEntity;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Pham Van Thanh
 */
public class Tables extends javax.swing.JPanel {

    private ToanCuc t = new ToanCuc();
    private String username = null;
    private String staff_username = t.getUsername();
    
    private tableCanteenDao tableDAO = new tableCanteenDao();
    private orderDao orderDAO = new orderDao();
    
    private ArrayList<TableCanteenEntity> listTables = tableDAO.selectTable();
    
    
    public Tables() {
        initComponents();
        tableDAO.loadTablesToTable(tblTables, listTables);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTables = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGopBan = new javax.swing.JButton();
        btnUpdateOrder = new javax.swing.JButton();
        btnChuyenBan = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnMangVe = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        tblTables.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tblTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bàn", "Tên bàn", "Trạng thái", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTables.setRowHeight(35);
        tblTables.setRowMargin(5);
        tblTables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTables);

        txtSearch.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Search :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 35, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 64, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 760, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnGopBan.setBackground(new java.awt.Color(0, 153, 204));
        btnGopBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnGopBan.setForeground(new java.awt.Color(255, 255, 255));
        btnGopBan.setText("Gộp bàn");
        btnGopBan.setEnabled(false);
        btnGopBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGopBanActionPerformed(evt);
            }
        });

        btnUpdateOrder.setBackground(new java.awt.Color(0, 153, 204));
        btnUpdateOrder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUpdateOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateOrder.setText("Cập nhật đơn");
        btnUpdateOrder.setEnabled(false);
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });

        btnChuyenBan.setBackground(new java.awt.Color(0, 153, 204));
        btnChuyenBan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChuyenBan.setForeground(new java.awt.Color(255, 255, 255));
        btnChuyenBan.setText("Chuyển bàn");
        btnChuyenBan.setEnabled(false);
        btnChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBanActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(0, 153, 204));
        btnCapNhat.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnBanHang.setBackground(new java.awt.Color(0, 153, 204));
        btnBanHang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBanHang.setForeground(new java.awt.Color(255, 255, 255));
        btnBanHang.setText("Ðơn hàng mới");
        btnBanHang.setEnabled(false);
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnMangVe.setBackground(new java.awt.Color(0, 153, 204));
        btnMangVe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMangVe.setForeground(new java.awt.Color(255, 255, 255));
        btnMangVe.setText("Đơn mang về");
        btnMangVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMangVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGopBan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(btnUpdateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(btnMangVe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(btnGopBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50)
                    .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 260, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablesMouseClicked
        int id = tblTables.getSelectedRow();
        //int id = listTables.get(i).getId();
        if(listTables.get(id).getStatus() == 1){  // Ban nay dang duoc su dung
            btnUpdateOrder.setEnabled(true);
            btnBanHang.setEnabled(false);
            btnChuyenBan.setEnabled(true);
            btnGopBan.setEnabled(true);
        }
        else if(listTables.get(id).getStatus() == 0){   // Ban nay dang trong
            btnBanHang.setEnabled(true);
            btnUpdateOrder.setEnabled(false);
            btnChuyenBan.setEnabled(false);
            btnGopBan.setEnabled(false);
        }
    }//GEN-LAST:event_tblTablesMouseClicked

    private void btnGopBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGopBanActionPerformed
        int i = tblTables.getSelectedRow();
        t.setTable_id(listTables.get(i).getId());
        new GopBan().setVisible(true);
    }//GEN-LAST:event_btnGopBanActionPerformed

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
        int i = tblTables.getSelectedRow();
        if(listTables.get(i).getStatus() == 1){  // Ban nay dang duoc su dung
            //Cap nhat don hang
            JOptionPane.showMessageDialog(this, "Bàn này đang hoạt động !", "Thông báo lỗi", JOptionPane.DEFAULT_OPTION);
            // Truyen id cua table vao Toan Cuc
            t.setTable_id(listTables.get(i).getId());
            //
            new BanHang().setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void btnChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBanActionPerformed
        int i = tblTables.getSelectedRow();
        t.setTable_id(listTables.get(i).getId());
        new ChuyenBan().setVisible(true);
    }//GEN-LAST:event_btnChuyenBanActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        int i = tblTables.getSelectedRow();
        if(listTables.get(i).getStatus() == 0){   // Ban nay dang trong
            //Them don hang moi
            JOptionPane.showMessageDialog(this, "Bàn này đang trống !", "Thông báo lỗi", JOptionPane.DEFAULT_OPTION);
            t.setTable_id(listTables.get(i).getId());

            //Tao 1 don hang moi
            long millis = System.currentTimeMillis();
            Date order_date = new Date(millis);
            int status = 1;  //Trang thai dang hoat dong
            int payments = 0; // Trang thai thanh toan mac dinh
            int type = 0;  // Su dung tai quan mac dinh type = 0 (mang ve 1, online 2)

            //Tao 1 don hang moi
            orderDAO.insertOrderOnTable(username, order_date, status , payments, listTables.get(i).getId(), type, staff_username);

            //Cap nhat trang thai cua ban là dang hoat dong
            tableDAO.updateStatusTable(listTables.get(i).getId(), status);

            new BanHang().setVisible(true);
        }
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnMangVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMangVeActionPerformed
        int b = JOptionPane.showConfirmDialog(this, "Tạo một đơn hàng mang về ?", "Notice", JOptionPane.YES_NO_OPTION);
        if (b == 0) {
            //Tao 1 don hang moi
            long millis = System.currentTimeMillis();
            Date order_date = new Date(millis);
            int status = 1;  //Trang thai dang hoat dong
            int payments = 0; // Trang thai thanh toan mac dinh
            int type = 1;  // Su dung mang ve mac dinh type = 1

            // so ban 0 : khong co ban nao co so ban 0  (chi su dung de ban mang ve)
            t.setTable_id(0);
            //Tao 1 don hang mang ve moi
            orderDAO.insertOrderMangVe(username, order_date, status, payments, type, staff_username);

            new BanHang().setVisible(true);
        }
    }//GEN-LAST:event_btnMangVeActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        listTables = tableDAO.selectTable();
        tableDAO.loadTablesToTable(tblTables, listTables);
    }//GEN-LAST:event_btnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChuyenBan;
    private javax.swing.JButton btnGopBan;
    private javax.swing.JButton btnMangVe;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTables;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
